### PR TITLE
Windows RISC-V toolchain build

### LINKED ISSUE #6: Wrong GCC version in Windows toolchain name
`riscv-toolchain-14-x64-win.zip` sounds like GCC 14.something.something, but in fact it is 13.2.0.

### LINKED ISSUE #8: Windows RISC-V build can be fixed
I was looking at [this commit](https://github.com/raspberrypi/pico-sdk-tools/commit/63a716bf0c50a37883a740e1526fde65af083493) and the associated [Actions run](https://github.com/raspberrypi/pico-sdk-tools/actions/runs/10620457593/job/29440279667).

I saw something similar in my own experiments, and it sounds completely unrelated, but the issue can be fixed by setting `core.autocrlf` to `false` in the git config. On Windows the build.ps1 file is used to clone needed repos so you could likely just add `-c core.autocrlf=false` to the command line there:

https://github.com/raspberrypi/pico-sdk-tools/blob/178ced38c49a08c19f979c36d7fed27cb1420b7b/build.ps1#L180

(Or set it globally beforehand, it's a throwaway CI runner.)

### PR DESCRIPTION
**Pull request by ndabas**
I've cleaned up the Windows builds and the riscv-gnu-toolchain build works fine.

However I couldn't get it to use our pre-cloned copy of GCC -- it appears to be an issue with paths that they've tried to [fix](https://github.com/riscv-collab/riscv-gnu-toolchain/pull/304) [twice](https://github.com/riscv-collab/riscv-gnu-toolchain/pull/1224) but it still does not work with an external GCC src on msys2/Windows.

That should not be a problem currently though because the gcc submodule points to the same branch that we are cloning ourselves, `releases/gcc-14`.

Can I ask what was the original motivation/intention behind cloning GCC separately?

Fixes #8.

Successful [actions run](https://github.com/ndabas/pico-sdk-tools/actions/runs/12329635039/job/34414166090) and [artifacts](https://github.com/ndabas/pico-sdk-tools/actions/runs/12329635039/artifacts/2321133597).

### CODE REVIEW

**Comment by will-v-pi** [comment]
Thanks, this looks good - could you target it at the `main` branch rather than `develop` (unlike the other pico repos, this one still uses `main` directly, `develop` was just to test the `develop` branches of the tools)? Make sure to rebase onto the latest `main`, as I've just pushed a commit to run our actions on PRs.

> Can I ask what was the original motivation/intention behind cloning GCC separately?

Because when this was released the toolchain was using GCC 13, so this provided a simple way to ensure we were using GCC 14 as recommended by some of our developers.

**Comment by ndabas** [comment]
Thanks, I have rebased on `main` and re-targeted the PR.

Sounds good on the GCC version then, I guess we could remove our clone of GCC entirely in a future refactor.

**Comment by ndabas** [comment]
@will-v-pi I see that you approved the workflow but it failed where it's trying to read an SSH key from secrets -- I guess that might have been needed when development was being done in private repos? So we could remove that step, or perhaps make it conditional, so it only runs on main?

**Comment by will-v-pi** [comment]
> @will-v-pi I see that you approved the workflow but it failed where it's trying to read an SSH key from secrets -- I guess that might have been needed when development was being done in private repos? So we could remove that step, or perhaps make it conditional, so it only runs on main?

If you just comment out those sections that would probably be best, so the code is still there if we need it later, but doesn't get used as it's not required right now.

**Comment by ndabas** [comment]
> If you just comment out those sections that would probably be best, so the code is still there if we need it later, but doesn't get used as it's not required right now.

Sure, done.

**Comment by will-v-pi** [comment]
Sorry, I meant for all the jobs (so the MacOS and Linux jobs as well)

**Comment by ndabas** [comment]
> Sorry, I meant for all the jobs (so the MacOS and Linux jobs as well)

Ah, okay, no worries -- done. I didn't want to touch the non-Windows related parts of the build so did not assume that.

**Comment by will-v-pi** [comment]
I'm happy to merge this as-is, and fix the MacOS build separately, as it looks like that was a pre-existing issue with the current Risc-V toolchain.

**Pull request merged**
